// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuration par défaut pour utiliser Firebase dans cette application.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions n\'a pas été configuré pour macOS - '
          'vous pouvez récupérer cette configuration via Firebase CLI',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions n\'a pas été configuré pour Windows - '
          'vous pouvez récupérer cette configuration via Firebase CLI',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions n\'a pas été configuré pour Linux - '
          'vous pouvez récupérer cette configuration via Firebase CLI',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions n\'est pas supporté pour cette plateforme.',
        );
    }
  }

  /// Configuration Firebase pour l'application Web.
  ///
  /// Pour configurer ces clés, suivez les instructions du guide de démarrage Firebase:
  /// https://firebase.google.com/docs/web/setup
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtu1xB90m8T3IGOO__IaocA6oe-S2ScRg',
    appId: '1:567037479335:web:9881438142f5a0a6860e82',
    messagingSenderId: '567037479335',
    projectId: 'argentenveloppes',
    authDomain: 'argentenveloppes.firebaseapp.com',
    storageBucket: 'argentenveloppes.firebasestorage.app',
  );

  /// Configuration Firebase pour l'application Android.
  ///
  /// Pour configurer ces clés, utilisez l'outil CLI FlutterFire:
  /// ```
  /// flutterfire configure
  /// ```
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_ANDROID_MESSAGING_SENDER_ID',
    projectId: 'argentenveloppes',
    storageBucket: 'argentenveloppes.firebasestorage.app',
  );

  /// Configuration Firebase pour l'application iOS.
  ///
  /// Pour configurer ces clés, utilisez l'outil CLI FlutterFire:
  /// ```
  /// flutterfire configure
  /// ```
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_IOS_MESSAGING_SENDER_ID',
    projectId: 'argentenveloppes',
    storageBucket: 'argentenveloppes.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );
}


